# Site settings
title: Mojito - Have a drink on me
email: hunter@missoula.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Mojito/blogster/" # the subpath of your site, e.g. /blog/
url: "http://mateu.github.io" # the base hostname & protocol for your site
twitter_username: mxhunter
github_username:  mateu

# Build settings
markdown: kramdown
